const DataList = [
    {
        "id": 1,
        "name": "Set for 2 people",
        "qty": '10',
        "counterValue": 1,
        "price": 89,
        "countPress": false,
        "menu": "[{\"categoryName\":\"Starter\",\"items\":[{\"itemName\":\"Chicken Tikka (6 pcs.)\",\"description\":\"Marinated chunks of chicken roasted in clay oven\",\"Quantity\":\"\"}]},{\"categoryName\":\"Main Course\",\"items\":[{\"itemName\":\"Paneer Jalfreji\",\"description\":\"Chunks of cottage cheese with capsicum, onion and tomato\",\"Quantity\":\"1\"},{\"itemName\":\"Butter Chicken\",\"description\":\"Chunks of chicken cooked with tomato butter sauce\",\"Quantity\":\"1\"}]},{\"categoryName\":\"Accompaniments\",\"items\":[{\"itemName\":\"Jeera Rice\",\"description\":\"Basmati rice fried with Indian cumin\",\"Quantity\":\"1\"},{\"itemName\":\"Garlic Naan\",\"description\":\"Indian bread with garlic roasted in clay oven\",\"Quantity\":\"1\"}]}]",
        "isImage": 1,
        "type": "c"
    },
    {
        "id": 8,
        "name": "Set for 4 people",
        "qty": '5',
        "counterValue": 1,
        "price": 149,
        "countPress": false,
        "menu": "[{\"categoryName\":\"Starter\",\"items\":[{\"itemName\":\"Onion  Bhajia (6 pcs.)\",\"description\":\"Onion slices battered and deep fried\",\"Quantity\":\"\"},{\"itemName\":\"Chicken Pakora  (6 pcs.)\",\"description\":\"Pieces of grilled chicken battered and deep fried.\",\"Quantity\":\"\"}]},{\"categoryName\":\"Main Course\",\"items\":[{\"itemName\":\"Palak Paneer\",\"description\":\"Spinach and chunks of cottage cheese cooked with Indian spices\",\"Quantity\":\"1\"},{\"itemName\":\"Chicken Jalfreji\",\"description\":\"Chunks of chicken cooked with mix vegetable\",\"Quantity\":\"1\"},{\"itemName\":\"Butter Mutton\",\"description\":\"Chunks of mutton cooked with tomato butter sauce\",\"Quantity\":\"1\"}]},{\"categoryName\":\"Accompaniments\",\"items\":[{\"itemName\":\"Safron Rice\",\"description\":\"Safron Rice\",\"Quantity\":\"1\"},{\"itemName\":\"Plain Rice\",\"description\":\"Basmati rice\",\"Quantity\":\"1\"},{\"itemName\":\"Butter Naan\",\"description\":\"Indian bread with butter roasted in clay oven\",\"Quantity\":\"2\"}]},{\"categoryName\":\"Dessert\",\"items\":[{\"itemName\":\"Gulab Jamun (4 pcs.)\",\"description\":\"Deep fried milk balls, soaked in sugar cadamom syrup\",\"Quantity\":\"\"}]}]",
        "isImage": 1,
        "type": "c"
    },
    {
        "id": 9,
        "name": "Set for 6 people",
        "qty": '20',
        "counterValue": 1,
        "price": 224,
        "countPress": false,
        "menu": "[{\"categoryName\":\"Starter\",\"items\":[{\"itemName\":\"Mix veg. Pakora (8 pcs.)\",\"description\":\"Mix vegetables battered and deep fried\",\"Quantity\":\"\"},{\"itemName\":\"Fish Pakora   (6 pcs.)\",\"description\":\"Pieces of fish battered and deep fried\",\"Quantity\":\"\"},{\"itemName\":\"Chicken Hariyali Tikka   (6 pcs.)\",\"description\":\"Chunks of chicken marinated with fresh herbs roasted in clay oven\",\"Quantity\":\"\"}]},{\"categoryName\":\"Main Course\",\"items\":[{\"itemName\":\"Paneer Makhni\",\"description\":\"Chunks of cottage cheese cooked with tomato butter sauce\",\"Quantity\":\"1\"},{\"itemName\":\"Dal Makhni\",\"description\":\"Black lentils cooked with tomato butter sauce\",\"Quantity\":\"1\"},{\"itemName\":\"Chicken Lababdar\",\"description\":\"Chunks of chicken cooked with cashew tomato onion sauce\",\"Quantity\":\"1\"},{\"itemName\":\"Mutton Curry\",\"description\":\"Chunks of mutton cooked with curry sauce\",\"Quantity\":\"1\"}]},{\"categoryName\":\"Accompaniments\",\"items\":[{\"itemName\":\"Lemon Rice\",\"description\":\"Basmati rice fried with turmeric, mustard seeds and fresh lemon juice\",\"Quantity\":\"2\"},{\"itemName\":\"Garlic Naan\",\"description\":\"Indian bread with garlic roasted in clay oven\",\"Quantity\":\"2\"},{\"itemName\":\"Methi Roti\",\"description\":\"Indian bread with fenugreek leaves roasted in clay oven\",\"Quantity\":\"2\"}]},{\"categoryName\":\"Dessert\",\"items\":[{\"itemName\":\"Gulab Jamun (6 pcs.)\",\"description\":\"Deep fried milk balls, soaked in sugar cadamom syrup\",\"Quantity\":\"\"}]}]",
        "isImage": 1,
        "type": "c"
    },
    {
        "id": 10,
        "name": "Green Salad",
        "qty": '5',
        "counterValue": 1,
        "description": "Freshly cut vegetables",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 7
    },
    {
        "id": 2,
        "name": "Brinjol & Cottage cheese salad",
        "qty": '45',
        "counterValue": 1,
        "description": "Deep fried brinjol and cottage cheese",
        "price": 15,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 6
    },
    {
        "id": 3,
        "name": "Chicken Tikka Salad",
        "qty": '7',
        "counterValue": 1,
        "description": "",
        "price": 15,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 5
    },
    {
        "id": 4,
        "name": "Dal soup",
        "qty": '1',
        "counterValue": 1,
        "description": "Freshly boiled Indian lentils with mix vegetables",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 11
    },
    {
        "id": 5,
        "name": "Tomato Soup",
        "qty": '1',
        "counterValue": 1,
        "description": "Tomato soup",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 6,
        "name": "Mushroom Palak Soup",
        "qty": '25',
        "counterValue": 1,
        "description": "Freshly cooked mushroom and spinach soup",
        "price": 14,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 7,
        "name": "Chicken Soup",
        "qty": '14',
        "counterValue": 1,
        "description": "Chicken soup with Indian herbs",
        "price": 14,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 8,
        "name": "Mutton Soup",
        "qty": '12',
        "counterValue": 1,
        "description": "Mutton soup with Indian herbs",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 9,
        "name": "Samosa (2 pcs.)",
        "qty": '30',
        "counterValue": 1,
        "description": "Crispy puffs stuffed with spicy potatoes and green peas",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 22
    },
    {
        "id": 100,
        "name": "Paneer Pakora (6 szt. \/ 6 pcs.)",
        "qty": '50',
        "counterValue": 1,
        "description": "Indian cottage cheese battered and deep fried",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 13
    },
    {
        "id": 11,
        "name": "Mix veg. Pakora (8 pcs.)",
        "qty": '20',
        "counterValue": 1,
        "description": "Mix vegetables battered and deep fried",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 12,
        "name": "Onion  Bhajia (6 pcs.)",
        "qty": '15',
        "counterValue": 1,
        "description": "Onion slices battered and deep fried",
        "price": 15,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 13,
        "name": "Chat Patta Paneer",
        "qty": '50',
        "counterValue": 1,
        "description": "Cubes of Indian cottage cheese tossed with Indian spices",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 14,
        "name": "Paneer Tikka",
        "qty": '5',
        "counterValue": 1,
        "description": "Chunks of cottage cheese marinated with curd and indian spices roasted in clay oven",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 14
    },
    {
        "id": 15,
        "name": "Harabhara Kebab",
        "qty": '13',
        "counterValue": 1,
        "description": "Mix vegetable cutlets with Indian spices",
        "price": 14,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 6
    },
    {
        "id": 16,
        "name": "Ghobi 65",
        "qty": '7',
        "counterValue": 1,
        "description": "Cauliflower battered golden fried with tomato and Indian spices",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 7
    },
    {
        "id": 17,
        "name": "Aloo Tikki",
        "qty": '8',
        "counterValue": 1,
        "description": "Golden fried potatoes with coriander and cumin",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 8
    },
    {
        "id": 18,
        "name": "Chicken Samosa (2 szt. \/ 2 pcs.)",
        "qty": '11',
        "counterValue": 1,
        "description": "Crispy puffs stuffed with spicy chicken, potatos and green peas",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 19,
        "name": "Mutton Samosa (2 szt. \/ 2 pcs.)",
        "qty": '14',
        "counterValue": 1,
        "description": "Crispy puffs stuffed with spicy mutton, potatos and green peas",
        "price": 18,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 20,
        "name": "Chicken Pakora  (6szt. \/ 6 pcs.)",
        "qty": '3',
        "counterValue": 1,
        "description": "Pieces of grilled chicken battered and deep fried.",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 5
    },
    {
        "id": 21,
        "name": "Chicken Lollipop (4 szt. \/ 4 pcs.)",
        "qty": '45',
        "counterValue": 1,
        "description": "Chicken wings coated in spice mixed gram flour and fried.",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 22,
        "name": "Chicken Tikka",
        "qty": '12',
        "counterValue": 1,
        "description": "Marinated chunks of chicken roasted in clay oven",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 8
    },
    {
        "id": 23,
        "name": "Chicken Hariyali Tikka",
        "qty": '15',
        "counterValue": 1,
        "description": "Chunks of chicken marinated with fresh herbs roasted in clay oven",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 24,
        "name": "Garlic Chicken Tikka",
        "qty": '60',
        "counterValue": 1,
        "description": "Chunks of chicken marinated with garlic roasted in clay oven",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 25,
        "name": "Murgh Malai Kebab",
        "qty": '20',
        "counterValue": 1,
        "description": "Supreme pieces of chicken marinated with cream and cheese roasted in clay oven",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"4\",\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 26,
        "name": "Tandoori Chicken",
        "qty": '8',
        "counterValue": 1,
        "description": "Leg and breast of chicken marinated with curd and tandoori spices roasted in clay oven",
        "price": 26,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 27,
        "name": "Fish Tikka",
        "qty": '6',
        "counterValue": 1,
        "description": "Butter fish marinated with fresh herbs and roasted in clay oven",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 28,
        "name": "Chicken 65",
        "qty": '3',
        "counterValue": 1,
        "description": "Chicken battered golden fried with tomato and Indian spices",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 29,
        "name": "Dal Tadka",
        "qty": '2',
        "counterValue": 1,
        "description": "Yellow and red lentils cooked with Indian spices",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 6
    },
    {
        "id": 30,
        "name": "Dal Makhni",
        "qty": '1',
        "counterValue": 1,
        "description": "Black lentils cooked with tomato butter sauce",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 31,
        "name": "Vegetable  Korma",
        "qty": '7',
        "counterValue": 1,
        "description": "Mix vegetables and chunks of cottage cheese cooked with cashewnut and cream sauce",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"4\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 6
    },
    {
        "id": 32,
        "name": "Mix Kadai Vegetable",
        "qty": '8',
        "counterValue": 1,
        "description": "Mix vegetables and chunks of cottage cheese cooked with capsicum, onion and tomato sauce",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"2\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 8
    },
    {
        "id": 33,
        "name": "Chana Masala",
        "qty": '7',
        "counterValue": 1,
        "description": "Chick peas cooked with Indian spices",
        "price": 20,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 34,
        "name": "Aloo Ghobi Curry",
        "qty": '45',
        "counterValue": 1,
        "description": "Chunks of potato and cauliflower cooked in onion tomato sauce",
        "price": 20,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 35,
        "name": "Aloo Bhindi",
        "qty": '7',
        "counterValue": 1,
        "description": "Chunks of potato and okra cooked with onion tomato sauce",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 36,
        "name": "Dahiwala Baingan",
        "qty": '3',
        "counterValue": 1,
        "description": "Chunks of fresh brinjol cooked with curd and coconut sauce",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 37,
        "name": "Vegetable kofta",
        "qty": '3',
        "counterValue": 1,
        "description": "Mix vegetables balls cooked with curry sauce",
        "price": 20,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 6
    },
    {
        "id": 38,
        "name": "Paneer Jalfreji",
        "qty": '2',
        "counterValue": 1,
        "description": "Chunks of cottage cheese with capsicum, onion and tomato",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 7
    },
    {
        "id": 39,
        "name": "Paneer Tikka Masala",
        "qty": '7',
        "counterValue": 1,
        "description": "Pieces of grilled Indian cottage cheese cooked with onion tomato sauce",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 8
    },
    {
        "id": 40,
        "name": "Palak Paneer",
        "qty": '60',
        "counterValue": 1,
        "description": "Spinach and chunks of cottage cheese cooked with Indian spices",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 15
    },
    {
        "id": 41,
        "name": "Paneer Makhni",
        "qty": '78',
        "counterValue": 1,
        "description": "Chunks of cottage cheese cooked with tomato butter sauce",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"4\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 12
    },
    {
        "id": 42,
        "name": "Matar Paneer",
        "qty": '46',
        "counterValue": 1,
        "description": "Chunks of cottage cheese and green peas cooked with tomato and cashew sauce",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 5
    },
    {
        "id": 43,
        "name": "Paneer Kofta",
        "qty": '30',
        "counterValue": 1,
        "description": "Cottage cheese balls cooked in cashew and cream sauce",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"4\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 44,
        "name": "Chicken Curry",
        "qty": '30',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with curry sauce",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 6
    },
    {
        "id": 45,
        "name": "Butter Chicken",
        "qty": '5',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with tomato butter sauce",
        "price": 26,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"4\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 29
    },
    {
        "id": 46,
        "name": "Chicken Tikka Masala",
        "qty": '4',
        "counterValue": 1,
        "description": "Chunks of grilled chicken cooked with onion tomato sauce",
        "price": 26,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 13
    },
    {
        "id": 47,
        "name": "Chicken Korma",
        "qty": '65',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with cream-cashew",
        "price": 28,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"4\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 20
    },
    {
        "id": 48,
        "name": "Chicken Lababdar",
        "qty": '56',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with cashew tomato onion sauce",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 5
    },
    {
        "id": 49,
        "name": "Chicken Palak",
        "qty": '1',
        "counterValue": 1,
        "description": "Spinach and chunks of chicken cooked with curry sauce",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 5
    },
    {
        "id": 50,
        "name": "Chicken Jalfreji",
        "qty": '1',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with mix vegetable",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 9
    },
    {
        "id": 51,
        "name": "Chicken Madras",
        "qty": '1',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with onion, capsicum and fresh hot green chilli",
        "price": 28,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"3\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 19
    },
    {
        "id": 52,
        "name": "Chicken Vindaloo",
        "qty": '1',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with Indian spice-sour sauce",
        "price": 28,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"3\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 8
    },
    {
        "id": 53,
        "name": "Methi Chicken",
        "qty": '23',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with fenugreek leaves with curry sauce",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 54,
        "name": "Ginger Chicken",
        "qty": '32',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with fresh ginger and Indian spices",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 55,
        "name": "Garlic Chicken",
        "qty": '22',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with fresh garlic and Indian spices",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 6
    },
    {
        "id": 56,
        "name": "Chicken Do Pyaza",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with onion-cashew sauce",
        "price": 30,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 57,
        "name": "Balti Chicken",
        "qty": '65',
        "counterValue": 1,
        "description": "Chunks of chicken cooked with capsicum, tomato with Indian spices",
        "price": 32,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"2\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 10
    },
    {
        "id": 58,
        "name": "Mutton Curry",
        "qty": '65',
        "counterValue": 1,
        "description": "Chunks of mutton cooked with curry sauce",
        "price": 30,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 59,
        "name": "Mutton Korma",
        "qty": '56',
        "counterValue": 1,
        "description": "Chunks of mutton cooked with cream- cashew sauce",
        "price": 32,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"4\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 60,
        "name": "Mutton Palak",
        "qty": '56',
        "counterValue": 1,
        "description": "Spinach and chunks of mutton cooked with curry sauce",
        "price": 30,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 61,
        "name": "Mutton Roghan Josh",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of mutton cooked with Indian spices and onion sauce",
        "price": 32,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 62,
        "name": "Mutton Madras",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of mutton cooked with onion, capsicum and fresh hot green chili",
        "price": 32,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"3\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 63,
        "name": "Kadai Mutton",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of mutton cooked with mix veg.",
        "price": 32,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"2\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 64,
        "name": "Bhuna Gosht",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of mutton cooked with Indian spices (dry)",
        "price": 30,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 65,
        "name": "Balti Mutton",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of mutton cooked with capsicum, tomato with Indian spices",
        "price": 36,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"2\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 66,
        "name": "Ginger Mutton",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of mutton cooked with fresh ginger and indian spices",
        "price": 35,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 67,
        "name": "Fish Curry",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of fish cooked with coconut based sauce",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 68,
        "name": "Fish Masala",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of fish cooked with onion tomato sauce",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 69,
        "name": "Fish Hydrabadi",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of fish cooked with fresh green Indian herbs",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"2\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 70,
        "name": "Garlic Fish",
        "qty": '10',
        "counterValue": 1,
        "description": "Chunks of fish cooked with fresh garlic and Indian spices",
        "price": 26,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 71,
        "name": "Prawn Curry",
        "qty": '10',
        "counterValue": 1,
        "description": "Prawns cooked with coconut and onion sauce",
        "price": 35,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 72,
        "name": "Prawn Jalfreji",
        "qty": '10',
        "counterValue": 1,
        "description": "Prawns cooked with mix vegetable and curry sauce",
        "price": 35,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 73,
        "name": "Prawn Chili Garlic Masala",
        "qty": '10',
        "counterValue": 1,
        "description": "Prawns cooked with garlic, chili and curry sauce",
        "price": 36,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"3\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 74,
        "name": "Vegetable Biryani",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice steamed with mix vegetables, chunks of cottage cheese and Indian spices",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 75,
        "name": "Chicken Biryani",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice steamed with boneless chicken and fresh Indian herbs",
        "price": 28,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 5
    },
    {
        "id": 76,
        "name": "Mutton Biryani",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice steamed with mutton and Indian spices",
        "price": 30,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 77,
        "name": "Prawn Biryani",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice steamed with prawns, cottage cheese and Indian spices",
        "price": 35,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 78,
        "name": "Plain Rice",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice",
        "price": 7,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 8
    },
    {
        "id": 79,
        "name": "Jeera Rice",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice fried with Indian cumin",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 80,
        "name": "Lemon Rice",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice fried with turmeric, mustard seeds and fresh lemon juice",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 81,
        "name": "Safron Rice",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 14,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 10
    },
    {
        "id": 82,
        "name": "Methi Pulao",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice fried with fenugreek leaves and cashew nuts",
        "price": 14,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 83,
        "name": "Peas Pulao",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice fried with green peas",
        "price": 14,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 84,
        "name": "Kashmiri Pulao",
        "qty": '10',
        "counterValue": 1,
        "description": "Basmati rice fried with fresh fruits",
        "price": 15,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"4\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 85,
        "name": "Chapati",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 5,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 86,
        "name": "Tandoori Roti",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread roasted in clay oven",
        "price": 6,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 4
    },
    {
        "id": 88,
        "name": "Plain Naan",
        "qty": '10',
        "counterValue": 1,
        "description": "Plain tandoori bread made from refined flour",
        "price": 7,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 24
    },
    {
        "id": 89,
        "name": "Butter Naan",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread with butter roasted in clay oven",
        "price": 9,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 25
    },
    {
        "id": 90,
        "name": "Garlic Naan",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread with garlic roasted in clay oven",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 41
    },
    {
        "id": 91,
        "name": "Keema Naan",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread stuffed with minced mutton and spices, roasted in clay oven",
        "price": 18,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"1\",\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 92,
        "name": "Kashmiri Naan",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread stuffed with cheese and fresh fruit, roasted in clay oven",
        "price": 15,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 93,
        "name": "Aloo Parantha",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread stuffed with potatoes and spices, roasted in clay oven",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 6
    },
    {
        "id": 94,
        "name": "Paneer Parantha",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread stuffed with cottage cheese and spices, roasted in clay oven",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 95,
        "name": "Mix Veg. Parantha",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread stuffed with mixed vegetables and spices, roasted in clay oven",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 771,
        "name": "Methi Roti",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian bread with fenugreek leaves roasted in clay oven",
        "price": 7,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 96,
        "name": "Plain Dosa",
        "qty": '10',
        "counterValue": 1,
        "description": "Pancake made from fermented rice and lentils",
        "price": 16,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 97,
        "name": "Masala Dosa",
        "qty": '10',
        "counterValue": 1,
        "description": "Pancake made from fermented rice and lentils, filled with spicy mix of onions and potatoes",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 8
    },
    {
        "id": 98,
        "name": "Chicken Masala Dosa",
        "qty": '10',
        "counterValue": 1,
        "description": "Pancake made from fermented rice and lentils, filled with spicy mix of chicken, onion and potatoes",
        "price": 28,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 99,
        "name": "Pudina Dosa",
        "qty": '10',
        "counterValue": 1,
        "description": "Pancake made from fermented rice and lentils with mint sause",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 100,
        "name": "Cheese Dosa",
        "qty": '10',
        "counterValue": 1,
        "description": "Pancake made from fermented rice and lentils with cheese",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 101,
        "name": "Plain Idli",
        "qty": '10',
        "counterValue": 1,
        "description": "Round, fluffy south Indian streamed bread, made from ground rice or rice flour mixed \r\nwith ground urad dal, salt.",
        "price": 22,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 102,
        "name": "Masala Idli",
        "qty": '10',
        "counterValue": 1,
        "description": "Round, fluffy south Indian streamed bread, made from ground rice or rice flour mixed \r\nwith ground urad dal, salt & spices",
        "price": 25,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 103,
        "name": "Uttapam",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian thick pancake made from rice flour",
        "price": 20,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 104,
        "name": "Onion Uttapam",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian thick pancake made from rice flour  mixed with onions and Indian spices",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 105,
        "name": "Tomato Uttapam",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian thick pancake made from rice flour mixed with tomatoes and Indian spices",
        "price": 24,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 106,
        "name": "Roasted Papad (2 szt.)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 4,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "[\"5\"]",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 107,
        "name": "Raita",
        "qty": '10',
        "counterValue": 1,
        "description": "Curd mixed with onion and cucumber",
        "price": 8,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 108,
        "name": "Gulab Jamun",
        "qty": '10',
        "counterValue": 1,
        "description": "Deep fried milk balls, soaked in sugar cardamom syrup",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 109,
        "name": "Kulfi (Mango, Pista, Badam)",
        "qty": '10',
        "counterValue": 1,
        "description": "Ice cream (Almonds, Pistachio & Mango)",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 110,
        "name": "Gajar Ka halwa",
        "qty": '10',
        "counterValue": 1,
        "description": "Carrot Pudding",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 111,
        "name": "Lassi Sweet",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian yogurt drink sweet",
        "price": 9,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 3
    },
    {
        "id": 112,
        "name": "Lassi Salty",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian yogurt drink salty",
        "price": 9,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 113,
        "name": "Mango Lassi",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian mango drink with yoghurt",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 18
    },
    {
        "id": 114,
        "name": "Banana Lassi",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian banana drink with yoghurt",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 115,
        "name": "Guava Lassi",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian guava drink with yoghurt",
        "price": 12,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 2
    },
    {
        "id": 116,
        "name": "Indian Tea (Chai)",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian tea with milk and masala",
        "price": 8,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 117,
        "name": "Indian Coffee",
        "qty": '10',
        "counterValue": 1,
        "description": "Indian coffee with milk and masala",
        "price": 8,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 118,
        "name": "Ayurvedic Tea",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 7,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 119,
        "name": "Black Tea",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 7,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 120,
        "name": "Espresso Small",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 7,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 789,
        "name": "Espresso Big",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 8,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 790,
        "name": "Indian Coffee",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 8,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 121,
        "name": "Ginger Lemon Drink (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 1
    },
    {
        "id": 122,
        "name": "Mango Juice (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 6,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 123,
        "name": "Lychee Juice (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 6,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 124,
        "name": "Guava Juice (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 6,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 125,
        "name": "Lemonade Sweet  (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 126,
        "name": "Lemonade Salty (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 10,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 127,
        "name": "Coca Cola \/ Zero (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 5,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 128,
        "name": "Coca Cola (500ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 6,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 129,
        "name": "Fanta  (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 5,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 130,
        "name": "Sprite  (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 5,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 131,
        "name": "Nestea lemon \/ peach  (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 5,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 132,
        "name": "Tonic  (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 6,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 133,
        "name": "Woda niegazowana \/ gazowana  (200ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 5,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 134,
        "name": "Woda niegazowana \/ gazowana  (500ml)",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 6,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    },
    {
        "id": 135,
        "name": "Juice Cappy Tomato \/ Orange \/ Apple",
        "qty": '10',
        "counterValue": 1,
        "description": "",
        "price": 5,
        "countPress": false,
        "nonVeg": "No",
        "icon_id": "",
        "isSpecial": "No",
        "topping_id": "",
        "isImage": 0,
        "type": "i",
        "liked": 0,
        "likes": 0
    }
]

export default DataList